// Crystal Butler
// GUI to turn on live streaming of AU data from FaceShift to a real-time animated avatar in Maya

if (`window -exists avatarLive`) {
    deleteUI avatarLive;
    windowPref -remove avatarLive;
}
window -title "Run Live Avatar" -widthHeight 200 100 avatarLive;
    columnLayout;
    button -label "Fire it Up!" -command updateAvatarLive;
    button -label "I've Had Enough" -command endTimer;
showWindow;
    