#!/bin/bash

#SBATCH --nodes=1
#SBATCH --mem=4GB
#SBATCH --time=2-00:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=cb2610@nyu.edu

cd /scratch/cb2610/Common_Crawl/WET_Paths/

for cc in $(cat wet_5600_aj)
	do wget https://commoncrawl.s3.amazonaws.com/$cc -P /scratch/cb2610/Common_Crawl/WET_Files/
done
